SolidSavings.Web/Controllers/UserController.cs
namespace SolidSavings.Web.Controllers
{
    using System;

    using Microsoft.AspNetCore.Mvc;

    using SolidSavings.Web.Infrastructure;
    using SolidSavings.Web.Logic;
    using SolidSavings.Web.Models;
    using SolidSavings.Web.Models.Enums;

    public class UserController : Controller
    {
        private readonly IUserBusiness userBusiness;

        public UserController(IUserBusiness userBusiness)
        {
            this.userBusiness = userBusiness;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return this.View("Login");
        }

        public IActionResult Register()
        {
            return this.View("Register");
        }

        [HttpPost]
        public IActionResult Register(LoginDto dto)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("Register");
            }

            this.userBusiness.RegisterNewUser(dto.Username);

            return this.View("Login");
        }

        [HttpPost]
        public IActionResult Login(LoginDto dto)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("Login");
            }

            var userToLogin = this.userBusiness.FindUser(dto.Username);

            HomeController.CurrentUserName = userToLogin.Value;
            HomeController.CurrentUserId = userToLogin.Key;
            return this.RedirectToAction("Incomes", "Home");
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HomeController.CurrentUserName = string.Empty;
            HomeController.CurrentUserId = Guid.Empty;
            return this.RedirectToAction("Login");
        }
    }
}

SolidSavings.Web/Views/User/Login.cshtml
@using SolidSavings.Web.Components
@using SolidSavings.Web.Models.Enums
@model SolidSavings.Web.Models.LoginDto
@section navigation
    {
    @await Component.InvokeAsync(typeof(LoginLogoViewComponent))
}
@section body
    {
    <div class="col-10">
        <div class="row section-title">
            <div class="offset-1 col-6">
                <h1>Logowanie</h1>
            </div>
        </div>
        <div class="row section-subtitle">
            <div class="offset-1 col-6">
                <h3>Aby zacząć działać z aplikacją zaloguj się wcześniej</h3>
            </div>
        </div>
        <div class="row ">
            <div class="col-5 offset-1">
                <form asp-action="Login" asp-controller="User" method="post">
                    <div class="form-group">
                        <label for="Username">Nazwa użytkownika</label>
                        <input asp-for="Username" type="text" id="Username" class="form-control" placeholder="Nazwa użytkownika">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-outline-primary pull-right" name="Action" value="@LoginActionType.Login">Zaloguj</button>
                    </div>

                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-5 offset-1">
                <a asp-action="Register" asp-controller="User" class="pull-right">Nie masz jeszcze konta? Zarejestruj się.</a>
            </div>
        </div>
    </div>
}

SolidSavings.Web/Views/User/Register.cshtml
@using SolidSavings.Web.Components
@using SolidSavings.Web.Models.Enums
@model SolidSavings.Web.Models.LoginDto
@section navigation
    {
    @await Component.InvokeAsync(typeof(LoginLogoViewComponent))
}
@section body
    {
    <div class="col-10">
        <div class="row section-title">
            <div class="offset-1 col-6">
                <h1>Rejestracja</h1>
            </div>
        </div>
        <div class="row section-subtitle">
            <div class="offset-1 col-6">
                <h3>Stali użytkownicy aplikacji oszczędzają do 34% więcej</h3>
            </div>
        </div>
        <div class="row ">
            <div class="col-5 offset-1">
                <form asp-action="Register" asp-controller="User" method="post">
                    <div class="form-group">
                        <label for="Username">Twoja użytkownika</label>
                        <input asp-for="Username" type="text" id="Username" class="form-control" placeholder="Nazwa użytkownika">
                    </div>
                    <div class="form-check form-check-inline">
                        <input asp-for="RegistrationType" type="radio"
                               id="TypeFree"
                               name="RegistrationType"
                               class="form-check-input" value="@UserRegistrationType.Free">
                        <label for="TypeFree" class="form-check-label">Opcja darmowa</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input asp-for="RegistrationType" type="radio"
                               id="TypePaid"
                               name="RegistrationType"
                               class="form-check-input" value="@UserRegistrationType.Paid">
                        <label for="TypePaid" class="form-check-label">Opcja płatna</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input asp-for="RegistrationType" type="radio"
                               id="TypeDemo"
                               name="RegistrationType"
                               class="form-check-input" value="@UserRegistrationType.Demo">
                        <label for="TypeDemo" class="form-check-label">Opcja demo</label>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn pull-right btn-outline-primary">Zarejestruj</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
}